# Generated by Django 3.1.3 on 2020-11-23 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Universityapp', '0002_attendancemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Universityapp.coursemodel'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
