# Generated by Django 3.1.3 on 2020-11-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universityapp', '0003_auto_20201124_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='Stdid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
