# Generated by Django 3.1.3 on 2020-11-23 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Universityapp', '0005_auto_20201124_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='Attendance',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='AssignmentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Assignment', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], max_length=100)),
                ('student_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Universityapp.studentmodel')),
            ],
        ),
    ]
