# Generated by Django 3.1.3 on 2020-11-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('Empid', models.IntegerField(primary_key=True, serialize=False)),
                ('Empname', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'employeetable',
            },
        ),
    ]
